apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: guestbook
        env:
        - name: DEBUG
          value: "true"
