apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- guestbook-debug.yaml

patchesJson6902:
- target:
    version: v1
    group: networking.k8s.io
    kind: Ingress
    name: guestbook
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: guestbook-dev.demo.akuity.io
    - op: replace
      path: /spec/tls/0/hosts/0
      value: guestbook-dev.demo.akuity.io
