apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesJson6902:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: guestbook-stage.demo.akuity.io
    - op: replace
      path: /spec/tls/0/hosts/0
      value: guestbook-stage.demo.akuity.io
  target:
    group: networking.k8s.io
    kind: Ingress
    name: guestbook
    version: v1

images:
- name: ghcr.io/akuity/guestbook
  newTag: 00009-554c55b
